### ISSUE TITLE
java.lang.NullPointerException while exporting Xcode 13.2.1 xcresult file

### ISSUE THREAD

**Issue by TsoyTim** [eroshenkoam/xcresults#33]
"xcresults export" command fails with:
java.lang.NullPointerException
	at io.eroshenkoam.xcresults.export.ExportCommand.runUnsafe(ExportCommand.java:101)
	at io.eroshenkoam.xcresults.export.ExportCommand.run(ExportCommand.java:86)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at io.eroshenkoam.xcresults.XCResults.main(XCResults.java:13)

Xcode  v 13.2.1

**Comment by NastyAlloys** [comment]
did you find solution?

**Comment by dmzhakov** [comment]
check if you have the `xcresulttool` plugin installed?
I got this error because export work on read output this [tools](https://github.com/eroshenkoam/xcresults/blob/master/src/main/java/io/eroshenkoam/xcresults/export/ExportCommand.java#L247)

**Comment by stanmb** [comment]
this solved the problem for me
`sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`
