### ISSUE TITLE
NullPointerException, when parsing .xcresult with failed test

### ISSUE THREAD

**Issue by Xanuriknur** [eroshenkoam/xcresults#44]

**Comment by Xanuriknur** [comment]
in last version, take error 

```
java.lang.NullPointerException
	at io.eroshenkoam.xcresults.export.Allure2ExportFormatter.lambda$format$1(Allure2ExportFormatter.java:95)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1649)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at io.eroshenkoam.xcresults.export.Allure2ExportFormatter.format(Allure2ExportFormatter.java:97)
	at io.eroshenkoam.xcresults.export.ExportCommand.exportTestSummary(ExportCommand.java:182)
	at io.eroshenkoam.xcresults.export.ExportCommand.lambda$runUnsafe$2(ExportCommand.java:140)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.eroshenkoam.xcresults.export.ExportCommand.runUnsafe(ExportCommand.java:139)
	at io.eroshenkoam.xcresults.export.ExportCommand.run(ExportCommand.java:90)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at io.eroshenkoam.xcresults.XCResults.main(XCResults.java:13)
```

**Comment by nick0602** [comment]
Encountering the same issue after updating to xcresults 1.13.0 (Xcode 14)

**Comment by eroshenkoam** [comment]
I will fix it soon, sry :(

**Comment by stanmb** [comment]
@eroshenkoam fix it please :)

**Comment by julie-camomile** [comment]
Waiting for this fix 😭

**Comment by stanmb** [comment]
@julie-camomile fixed here - https://github.com/eroshenkoam/xcresults/releases/tag/1.13.1
