### ISSUE TITLE
java.lang.NullPointerException while export merged xcresult report via xcrun xcresulttool merge

### ISSUE THREAD

**Issue by EgorovDmitry** [eroshenkoam/xcresults#48]
I faced this exception during the export xcresult report which was created by merging some xcresult by the command xcrun xcresulttool merge
The issue is reproduced on all versions after 1.12.0, on 1.12.0 there is no error
```
java.lang.NullPointerException
	at io.eroshenkoam.xcresults.export.Allure2ExportFormatter.getPosition(Allure2ExportFormatter.java:261)
	at io.eroshenkoam.xcresults.export.Allure2ExportFormatter.format(Allure2ExportFormatter.java:102)
	at io.eroshenkoam.xcresults.export.ExportCommand.runUnsafe(ExportCommand.java:141)
	at io.eroshenkoam.xcresults.export.ExportCommand.run(ExportCommand.java:88)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at io.eroshenkoam.xcresults.XCResults.main(XCResults.java:13)
```

**Comment by alexnot95** [comment]
See the same issue on the 1.15.0 version

**Comment by gulyayko** [comment]
same issue, 1.15.0

**Comment by mbeysulen** [comment]
The same issue exists in the latest version and older versions. I think it is from a file while exporting xcresult. I hope it will be resolved soon
