### ISSUE TITLE
Gettin error while running export

### ISSUE THREAD

**Issue by Aren-Am** [eroshenkoam/xcresults#66]
I installed xcresults by the following way:

```
brew install allure
DOWNLOAD_URL="https://github.com/eroshenkoam/xcresults/releases/download/1.13.1/xcresults"
curl -sL "${DOWNLOAD_URL}" -o ./xcresults
chmod +x ./xcresults
```

After running this command I see the following error:

`./xcresults export TestResult.xcresult allure-results
`

```
java.lang.NullPointerException
	at io.eroshenkoam.xcresults.export.ExportCommand.runUnsafe(ExportCommand.java:105)
	at io.eroshenkoam.xcresults.export.ExportCommand.run(ExportCommand.java:90)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at io.eroshenkoam.xcresults.XCResults.main(XCResults.java:13)
```

**Comment by Aren-Am** [comment]
@eroshenkoam Could you please take a look and help if it is possible?

**Comment by Aren-Am** [comment]
Figured out
