### ISSUE TITLE
java.lang.NullPointerException while export xcresult report from Xcode 18

### ISSUE THREAD

**Issue by myAnotherGithubProfile** [eroshenkoam/xcresults#73]
Xcode 16.0 (16A242), xcresults 1.18. This issue is consistently reproduced when I run the command **./xcresults export myXcresult.xcresult ~/allure-results**
```
Delete existing output directory...
java.lang.NullPointerException
at io.eroshenkoam.xcresults.export.ExportCommand.runUnsafe(ExportCommand.java:116)
at io.eroshenkoam.xcresults.export.ExportCommand.run(ExportCommand.java:101)
at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
at picocli.CommandLine.access$900(CommandLine.java:145)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
at picocli.CommandLine.execute(CommandLine.java:1904)
at io.eroshenkoam.xcresults.XCResults.main(XCResults.java:13)
```

**Comment by rkolchakov** [comment]
We have also encountered this error while exporting test results 🥺

**Comment by rkolchakov** [comment]
@eroshenkoam Hi, would you be able to assist us in resolving an issue?

**Comment by rkolchakov** [comment]
@eroshenkoam Hi. I wanted to kindly ask if there have been any updates on the issue?

**Comment by vince1393** [comment]
We're having this issue as well. Any update on this?

**Comment by tutrieuchau** [comment]
@vince1393 I have try the package which @havebeenfitz update, I can run it in the first time, but after that all failed, that magic.

**Comment by tutrieuchau** [comment]
@vince1393 I pull the code then update. Now it can run, you can try to use it.
[Uploading xcresults.zip…]()

**Comment by eroshenkoam** [comment]
Hey everyone! 🙏

Apologies for the delay in resolving this issue — the past couple of weeks have been quite busy. But I’m happy to say that we’ve finally addressed it in the [1.19.0](https://github.com/eroshenkoam/xcresults/releases/tag/1.19.0) release! 🚀

Big thanks to everyone who contributed and provided feedback in this ticket.

Let’s keep pushing forward! 💪
